variable:
  credit: 0.0135
  # paypal:
  # molpoints:
  boost: 0.013
  wechatpaymy: 0.01
  # wechatpaymy_offline:
  grabpay: 0.013
  mb2u_qrpay_push: 0.01
  tng_ewallet: 0.013
  shopeepay: 0.013
  rpp_duitnowqr: 0.0095
  alipay: 0.013
  alipayplus: 0.013
  unionpay: 0.023
  fpx: 0.012
  fpx_b2b: 0.012
  # ioupay_pw: 
  atome: 0.05
  # pace:

fixed:
  fpx_mb2u: 1
  mb2u: 1
  fpx_cimbclicks: 1
  cimb_clicks: 1
  fpx_rhb: 1
  rhb_onl: 1
  fpx_pbb: 1
  pbebank: 1 
  fpx_hlb: 1
  hlb_onl: 1
  fpx_bimb: 1
  fpx_amb: 1
  amb_w2w: 1
  fpx_abmb: 1
  alb_onl: 1
  fpx_abb: 1
  affin_epg: 1
  fpx_bmmb: 1
  fpx_bkrm: 1
  fpx_bsn: 1
  fpx_ocbc: 1
  fpx_uob: 1
  fpx_hsbc: 1
  fpx_scb: 1
  fpx_kfh: 1
  fpx_b2b_amb: 1.4
  fpx_b2b_hlb: 1.4
  fpx_b2b_uob: 1.4
  fpx_b2b_abb: 1.4
  fpx_b2b_hsbc: 1.4
  fpx_m2e: 1.4
  fpx_b2b_cimb: 1.4
  fpx_b2b_bimb: 1.4
  fpx_b2b_rhb: 1.4
  fpx_b2b_pbb: 1.4
  fpx_b2b_kfh: 1.4
  fpx_b2b_deutsche: 1.4
  fpx_b2b_abmb: 1.4
  fpx_b2b_scb: 1.4
  fpx_b2b_ocbc: 1.4
  fpx_b2b_bmmb: 1.4
  fpx_emandate: 1.4
  fpx_directdebit: 1.4
  fpx_agrobank: 1
  fpx_b2b_agrobank: 1.4
  fpx_b2b_abbm: 1.4
  fpx_b2b_citibank: 1.4
  fpx_b2b_bkrm: 1.4
  fpx_b2b_pbbe: 1.4
  fpx_b2b_uobr: 1.4
  fpx_emandate_abb: 1.4
  fpx_directdebit_abb: 1.4


# visa:
# - credit: 1.35%
# - creditAB: 1.35%

# fpx_b2c:
# - bimb: 1
# - mb2u: 1
# - pbb: 1
# - cimbclicks: 1
# - amonline: 1
# - hlbconnect: 1
# - rhbnow: 1
# - fpx_ocbc: 1
# - fpx_scb: 1
# - fpx_abb: 1
# - bankrakyat: 1
# - bankmuamalat: 1
# - fpx_kfh: 1
# - fpx_bsn: 1
# - fpx_abmb: 1
# - fpx_uob: 1
# - fpx_hsbc: 1
# - fpx_agrobank: 1

# duitnow_obw:
# - rpp_rtp_abb: 0.95%
# - rpp_rtp_abmb: 0.95%
# - rpp_rtp_agrobank: 0.95%
# - rpp_rtp_amb: 0.95%
# - rpp_rtp_cimbclicks: 0.95%
# - rpp_rtp_bimb: 0.95%
# - rpp_rtp_bkrm: 0.95%
# - rpp_rtp_bmmb: 0.95%
# - rpp_rtp_bsn: 0.95%
# - rpp_rtp_hlb: 0.95%
# - rpp_rtp_hsbc: 0.95%
# - rpp_rtp_kfh: 0.95%
# - rpp_rtp_mb2u: 0.95%
# - rpp_rtp_ocbc: 0.95%
# - rpp_rtp_pbb: 0.95%
# - rpp_rtp_rhb: 0.95%
# - rpp_rtp_scb: 0.95%
# - rpp_rtp_uob: 0.95%

# fpx_b2b:
# - fpx_b2b_amb: 1.4
# - fpx_b2b_hlb: 1.4
# - fpx_b2b_uob: 1.4
# - fpx_b2b_abb: 1.4
# - fpx_b2b_cimb: 1.4
# - fpx_b2b_bimb: 1.4
# - fpx_b2b_pbb: 1.4
# - fpx_b2b_rhb: 1.4
# - fpx_b2b_hsbc: 1.4
# - fpx_m2e: 1.4
# - fpx_b2b_bnp: 1.4
# - fpx_b2b_abbm: 1.4
# - fpx_b2b_citibank: 1.4
# - fpx_b2b_bkrm: 1.4
# - fpx_b2b_pbbe: 1.4
# - fpx_b2b_uobr: 1.4
# - fpx_b2b_agrobank: 1.4
# - fpx_emandate: 1.4
# - fpx_emandate_abb: 1.4

# duitnow:
# - rpp_duitnowqr: 0.95%

# wallet:
# # - razerpay
# # - molpoints
# - tng_ewallet: 1.3%
# - boost: 1.3%
# - grabpay: 1.3%
# - mb2u_qrpay_push: 1.0%
# - shopeepay: 1.3%

# buy_now_pay_later:
# - atome: 5.0%
# # - pace
# # - IOUPay-PW